openapi: 3.0.1
info:
  title: circlegen
  description: circlegen
  x-cortex-git:
    gitlab:
      repository: ads/adsstaff/circlegen
  x-cortex-tag: adsstaff_circlegen
  x-cortex-type: service
  x-cortex-groups:
  - script
  x-cortex-owners:
  - type: group
    name: ads-se
    provider: CORTEX
  x-cortex-domain-parents:
  - tag: adsstaff
  x-cortex-static-analysis:
    sonarqube:
      project: adsstaff_circlegen
  x-cortex-custom-metadata:
    github: https://github.com/fresh8gaming/circlegen
    codebase-type:
      type: script
      description: https://sportradar.slack.com/archives/C02PFBUALP4/p1689156840940119
